#!/usr/bin/env python3
"""Split the 秒克 album Vue SFC into its template / script / style blocks and
surface the generator's data tables.

Usage:
    python3 artifacts/parse_module.py input/social_album.vue

The four riddles (riddle1 / box-puzzle / maze-photo / rebus-grid) are all
generated by this one module, so its script block holds the lookup tables that
every guess so far has failed to reconstruct: which square pattern maps to
which picture, how the 7x2 grid and its question mark are placed, how the maze
and its animals are laid out, and how the three rebus rows are drawn.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

BLOCK = re.compile(r"<(template|script|style)([^>]*)>(.*?)</\1>", re.S)
# things worth pulling out of the script block first
INTERESTING = ("sq--", "riddle1", "box-", "maze", "rebus", "huang", "燕", "姓",
               "const ", "let ", "= [", "= {", "answer", "Answer", "random")


def main() -> None:
    path = Path(sys.argv[1] if len(sys.argv) > 1 else "input/social_album.vue")
    src = path.read_text(encoding="utf-8", errors="replace")
    print(f"# {path}  ({len(src)} bytes)\n")
    blocks = BLOCK.findall(src)
    if not blocks:
        print("(no SFC blocks found — dumping head)")
        print(src[:3000])
        return
    for tag, attrs, body in blocks:
        print(f"===== <{tag}{attrs}>  {len(body)} bytes =====")
        if tag == "script":
            # array / object literals are where the lookup tables live
            for m in re.finditer(r"(?:const|let|var)\s+(\w+)\s*=\s*([\[{][\s\S]{0,1200}?)\n(?=\s*(?:const|let|var|function|export|\}|$))", body):
                print(f"\n--- {m.group(1)} ---\n{m.group(2)[:1200]}")
            print("\n--- lines mentioning riddle keywords ---")
            for line in body.splitlines():
                if any(k in line for k in INTERESTING) and len(line.strip()) < 300:
                    print("   ", line.strip())
        else:
            print(body[:2000])
        print()


if __name__ == "__main__":
    main()
