# -*- coding: utf-8 -*-
"""Shared dictionaries (no printing)."""
import os, re
HERE = os.path.dirname(os.path.abspath(__file__))
BIG = set(w.strip().upper() for w in open(os.path.join(HERE,'words_alpha.txt')) if len(w.strip())>=3)
COMMON = set(w.strip().upper() for w in open(os.path.join(HERE,'google10k.txt')) if len(w.strip())>=3)
COMMON |= set('AN AT TO OF IN IS IT HE BE OR ON AS BY WE DO IF MY UP SO NO US AM ME GO'.split())
COMMON |= set('''SEA SKY SUN MOON STAR EARTH LAND FIRE WIND RAIN SNOW ICE GOLD IRON JADE SILK
HORSE COW OX PIG DOG CAT BIRD FISH PINE OAK ROSE LOTUS FLOWER GRASS TREE LEAF WOOD STONE ROCK
HILL PEAK LAKE RIVER POND WELL CAPE HORN BAY PORT CITY TOWN HOUSE HALL GATE ROAD TOWER DEW MIST
RED WHITE BLACK BLUE GREEN PURPLE GOLDEN SILVER CLOUD FOG WAVE TIDE SAND DUST GOOD FINE HOPE
JOY LOVE PEACE LUCK FATE LIFE LIVE LATE FAST SLOW LONG SHORT HIGH LOW BIG TINY GREAT MIDDLE
CENTER NORTH SOUTH EAST WEST LEFT RIGHT OUTER INNER KING QUEEN LORD SAINT ANGEL DRAGON TIGER
LION BEAR WOLF DEER CRANE SONG ODE HYMN POEM VERSE DANCE MUSIC DREAM SOUL HEART MIND HAND FOOT
HEAD FACE EYE HAIR SKIN BONE BLOOD MILK HONEY WINE TEA RICE BREAD CAKE MEAT SALT SUGAR SWEET
WARM COOL COLD HOT DRY WET SOFT HARD LIGHT DARK BRIGHT POWER FORCE STRONG RICH WISE BRAVE
CLEVER SKILL ART CRAFT FUN PLAY GAME WORK REST SLEEP WAKE MEET PART GIVE TAKE COME RUN WALK
FLY SWIM JUMP DOT LINE POINT EDGE SIDE FRONT BACK TOP END FIRST LAST NEW OLD YOUNG MAN MEN
HAIL SHOW PHONE'''.split())
PLACES = set()
for line in open(os.path.join(HERE,'cities15000.txt'), encoding='utf-8'):
    p = line.rstrip('\n').split('\t')
    if len(p) < 15: continue
    k = re.sub(r'[^A-Z]','',(p[2] or p[1]).upper())
    if 3 <= len(k) <= 14 and int(p[14] or 0) >= 30000: PLACES.add(k)
LOAN = set(open(os.path.join(HERE,'loanwords.txt')).read().upper().split())
DICT = BIG | PLACES | LOAN
